language: python
python:
- '3.6'
branches:
  only:
  - master
sudo: required
env:
  global:
  - CPLUS_INCLUDE_PATH=/usr/include/gdal
  - C_INCLUDE_PATH=/usr/include/gdal
  - IMAGE_NAME=geocomm/lostifier
  - REMOTE_IMAGE_URL=709177336629.dkr.ecr.us-west-2.amazonaws.com/geocomm/lostifier
  - AWS_DEFAULT_REGION=us-west-2
  - secure: f4QoQecJhCfg+wCuGyaGK8SnB0RTJvU0bFtupFIIw6AXMFRHKtXaZl4kaPZ1HwA1pDW/BIahRsJAqkQOPdo0m+JuFDReDIyNCMwaDKx1JBcI1XErVm9F5i8RU7CP+jbYbYzjng9+ZFvu4OulTnWoEBFTmJFmI3A4PsB9QpQKdQFV7vPBdRXGH6zdVJcS9spDIoP1gpjGmKhjBVIT/xvtNMl9sS1wk9UyBF8SnOWClQ5ihXWBO/d457k3CFmCtBtwJYDxPZipD18egSl5a9ssQEFOWeZ46FN4iA0YsICxEyUjq2Zibrng4Q8+iEYAlLaSvOfymYmqua4Plgr8WpgtBl2jR4aWliHyN0tJDs3vYKENIf+PHZ3u6SuT0gaedg7tbUP+zPzZJvkn8oIQjLzhuDFkj/L1l2Rhj3QzoErTmIr+ktbjnBwubfwKUKh4cmzK/MZ7hMkcQ2V0IrbpKL8dLi++b2bUL5uBsW0gqA/6JDEjsC1FFm9n8AyGP9eCmf4qddzt+lFIdeRhrzOS8H99lpFYRVSe9FqwZJsa+/mjnSrNzR37z9oQvd4KjC2tgotwKvAyVp+XCQF4jWoLMJQPNgZfqeD963OsWvSsSOw8reLFaLrbYykBFX+yaluljKi5rpjcKjUkpqr6JDNOhk3rkNdNzvukRmvXmpXRx7zxiIY=
  - secure: 1dzutkym6vigrF1r246hMa9MicUcL6M4bNhuSAvqy17wBMGbJkYnE7Wauvqnr2Doj3PiOrXeYoHTr2M7ZkU6IdVVW/2pIfqvtGXSaiyO+0ocF++RvO+mgxWJ3+lRTR55ffYdVq5ffjyb6u6lwzPddZqrzem9TPpjenBktqlOEVWvVGgI+lhoTKQCZs69eLbm8GWHQyqeMMPzKXOkLgdt8rs9kshofBPBEHukg319HcsqhSHllANdg1xSOaPsTlW3n4svryfGLIlbrrdo6ss7UF1s1ikuFMdFZzibfj2e3xsDEv3PN3jIG0sprsEc1wIj1D/A6ThAFg1kaeA8FPp3QkxOw3GN/2/VJ7ooafmbtmojQr+fOkMPtkRmN6DfgbMeRMatSjKmmNNR4v2q/bpIc90AvpKg9OhXnYuv/kwFJZ1dZtocn6Cdevq1TXTE3N0VXt5qXhWgdZCYoYReVx1fP659WRvVZv0oEhG6CJ4U/ubqGb0YWUx1i6tchsFtCReEI4eJKb4ps8WkYMETz6cYMkoDSoxIEXD5rjTLqTVjiQm5V/WB7eiJ0Lhg/egQs5OWkeD6JYs2LogSN+JeBf+kPpyqKIdKzUtFqpChA8FMOus7MiWcbVwABeUUDkx1RlMi7WEsrxOXKSWHN+R3E9ISy2XTmms7rk29TmlTQHGeuCU=
  - secure: Tztsmany79wErLXgsapgzhcjxWqwk5nmmh7UTIUNSBWfpFC2Tu/8y8sHmxayYk865dKFJC2iKo2h43JxWnJKjZmdZzpbe3ylOH9lqNGREskXdl0s6ibuYuAlOtJZUK5046YmqUirSrZWdcoKcbd7lToO3IpNnACHUpn/7+b3PLRrSF6O7u3nHcVeLI/PmsV97tA7+20q1NzuNnTnw3seUDfItlgKXhtUFhwu9zNGeB6pxH5/OWRKIZdB3NPXf6qB9ZeIuAL4zGukb5FOHagPY9ve7VCgpfNqHIuHReQUzuM5HN51+RG0JkBabCJslI9XI1gocdFYuCSCBHO3jWbDHii7YL6pO/RmxIDlka2NKvjv8xl4yiOJIdH5uKeB3/6la+cvQWayS81zigMXYfS4Cw1wkmwRl09Xs4AY5Imdbbqv9VfUoGcXxWyocmaTf47M9fUCkMwqMVsjBCUbbQLAAJOtMQxUwELVKpO+fvu/sKNUCyWk6ETo3VLjTa3rPUo5qPBpBPrg2afQvWJaFswFHj7lrjS3Nor0+N4/PtnvBCgYHGZOkGNwTBDqg7d8KbotwA/0UR8G6pHQJylx4RWLUwzBz0bPkKifu9tpEoGALyP+b1yj/cpPWPXlIksrats+AHw87gsV00lXZmWN2rjdsp6faTaVv7oTsUcKEjsPKn4=
services:
- docker
before_script:
- chmod +x ./lostifier_push.sh
script:
- pytest --cov=lostifier ./tests/test_*
install:
- pip install -r requirements.txt --extra-index-url $GEMFURY_URL
- pip install coverage
- pip install pytest-cov
- pip install awscli
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ppa -y
- sudo apt-get update -q
- sudo apt-get install -y gdal-bin libgdal-dev -y
after_success:
- coverage report
- python setup.py sdist
- curl -F package=@./dist/lostifier-3.0.$TRAVIS_BUILD_NUMBER.tar.gz $GEMFURY_URL
- ./lostifier_push.sh
notifications:
  webhooks: https://outlook.office.com/webhook/8e85e59c-da42-4a8e-ad98-a7f0173b2a0e@ba05d72b-83fc-45fc-873b-b2841e0752de/TravisCI/a0a34daa96724c4cb6309283da957e6a/56b9b902-14c4-4a02-8944-45059ec4524c
